ame: Python Application Test

on:
  push:
    branches: 
      - main

jobs:

  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10"]

    steps:
      - name: Install dependencies
        run: |
            pip install --no-cache-dir --upgrade -r requirements.txt

      - name: Start Image
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000

      - name: test unitario
        run: |
          python -m unittest discover tests

      - name: subir imagen
        run: |
          docker build -t devco/fast-api-example:latest